### ISSUE TITLE
Can not change both series and options at the same time

### ISSUE THREAD

**Issue by thanh01pmt** [apexcharts/vue3-apexcharts#136]
Dear, 
I'd love the lib.
However, I get into a trouble when trying to change both series and options at the same time.
Currently, I can change the series but the labels of those series are not reactive.
When I try to force options to change. I will get this error:

`
apexcharts.common.js:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at apexcharts.common.js:6:517937
    at wrappedFn (reactivity.esm-bundler.js:861:19)
    at Array.map (<anonymous>)
    at apply (reactivity.esm-bundler.js:869:27)
    at Proxy.map (reactivity.esm-bundler.js:793:12)
    at Proxy.value (apexcharts.common.js:6:517861)
    at Proxy.value (apexcharts.common.js:38:35390)
    at watch.deep (vue3-apexcharts.js:122:46)
    at callWithErrorHandling (runtime-core.esm-bundler.js:199:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:206:17)
`

Here is my code (with VueJs, Quasar Framework).

``` vue
<template>
    <apexchart
        v-if="dynamicOptions"
        type="donut"
        :options="dynamicOptions"
        :series="dynamicSeries"
        height="350"
    />
</template>

<script setup>
import { ref, onMounted, onUnmounted, reactive } from 'vue';

let dynamicSeries = ref([]);
let dynamicOptions = ref({  // Sử dụng reactive
    chart: { type: 'donut' },
    labels: [],
    noData: { 
      text: "Không có dữ liệu",
      align: "center",
      verticalAlign: "middle",
      offsetX: 0,
      offsetY: 0,
      style: { color: "#888", fontSize: "14px" } 
    }
});

let intervalId;

function updateChartData() {
    const numLabels = Math.floor(Math.random() * 4) + 3;
    const labels = [];
    const series = [];

    for (let i = 0; i < numLabels; i++) {
        labels.push(String.fromCharCode(65 + i));
        series.push(Math.floor(Math.random() * 100));
    }

    //dynamicOptions.value = Object.assign({}, dynamicOptions.value, { labels: labels});
    dynamicSeries.value = series;

}

onMounted(() => {
    updateChartData();
    intervalId = setInterval(updateChartData, 1000);
});

onUnmounted(() => {
    clearInterval(intervalId);
});
</script>
```

**Comment by thanh01pmt** [comment]
For anyone who gets into the same trouble, I solved this by forcing the chart to re-render.

```
<template>
    <apexchart
        v-if="dynamicOptions"
        type="donut"
        :options="dynamicOptions"
        :series="dynamicSeries"
        :key="chartKey"
        height="350"
    />
</template>

<script setup>
import { ref, onMounted, onUnmounted, reactive } from 'vue';

let chartKey = reactive(0);
const dynamicSeries = ref([]);
let dynamicOptions = reactive({ 
    chart: { type: 'donut' },
    labels: [],
    noData: { 
      text: "Không có dữ liệu",
      align: "center",
      verticalAlign: "middle",
      offsetX: 0,
      offsetY: 0,
      style: { color: "#888", fontSize: "14px" } 
    }
});

let intervalId;

function updateChartData() {
    const numLabels = Math.floor(Math.random() * 4) + 3;
    const labels = [];
    const series = [];

    for (let i = 0; i < numLabels; i++) {
        labels.push(String.fromCharCode(65 + i));
        series.push(Math.floor(Math.random() * 100));
    }

    dynamicSeries.value = series;

    dynamicOptions = {
      ...dynamicOptions,
      labels: labels,
    };

    chartKey++;
}

onMounted(() => {
    updateChartData();
    intervalId = setInterval(updateChartData, 3000);
});

onUnmounted(() => {
    clearInterval(intervalId);
});
</script>
```
